[phases.setup]
nixPkgs = ["python39", "gcc", "postgresql", "python39Packages.pip"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 wsgi:app" 
