[phases.setup]
nixPkgs = ["python39", "gcc", "postgresql", "python39Packages.pip", "python39Packages.setuptools"]

[phases.install]
cmds = ["python3.9 -m ensurepip --upgrade", "python3.9 -m pip install -r requirements.txt"]

[start]
cmd = "gunicorn --bind 0.0.0.0:$PORT --workers 4 --timeout 120 wsgi:app"
